# Generated by Django 3.0.3 on 2020-04-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiUsers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='title',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='zip',
        ),
    ]
