# Generated by Django 3.0.3 on 2020-05-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiUsers', '0003_userprofile_mandarin_known_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='english_known_words',
            field=models.TextField(blank=True, default=''),
        ),
    ]
