# Generated by Django 3.0.3 on 2020-05-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiUsers', '0004_userprofile_english_known_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='english_study_words',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mandarin_study_words',
            field=models.TextField(blank=True, default=''),
        ),
    ]
